SeruBans:
  messages:
    ban:
      GlobalBanMessage: '&f%kicker% banned %victim% for %reason%'
      BanMessage: '&cYou have been banned by &4%kicker%, &cfor &4%reason%'
    kick:
      GlobalKickMessage: '&f%kicker% kicked %victim% for %reason%'
      KickMessage: '&fYou have been kicked by %kicker%, for %reason%'
    warn:
      WarnMessage: '&f%victim% has been warned by %kicker%, for %reason%'
      WarnPlayerMessage: '&fYou were warned by %kicker%, for %reason%'
    tempban:
      GlobalTempBanMessage: ''
      TempBanMessage: ''
    UnBanMessage: ''
  MySql:
    database: ''
    user: ''
    password: ''
