name: SeruBans
main: net.serubin.serubans.SeruBans
version: 0.1

commands:
   ban:
      description: Bans player
      usage: /<command> <player> <reason> - bans player
   kick:
      description: kicks player
      usage: /<command> <player> <reason> - kicks player
   warn:
      description: warns player
      usage: /<command> <player> <reason> - warns player
   unban:
      description: unbans player
      usage: /<command> <player> - unbans player
   sbuser:
      description: debug
      usage: /<command> - lists users