name: SeruBans
main: net.serubin.serubans.SeruBans
version: 0.1

commands:
   ban:
      description: Bans player
      usage: /<command> <player> <reason> - bans player
   kick:
      description: kicks player
      usage: /<command> <player> <reason> - kicks player
   warn:
      description: wanrs player
      usage: /<command> <player> <reason> - warns player