name: SeruBans
main: net.serubin.serubans.SeruBans
version: 1.0.1

commands:
   ban:
      description: Bans player
      usage: /<command> <player> <reason> - bans player
   tempban:
      description: tempbans player
      usage: /<command> <player> <amount> <unit> <reason> - tempbans player
   kick:
      description: kicks player
      usage: /<command> <player> <reason> - kicks player
   warn:
      description: warns player
      usage: /<command> <player> <reason> - warns player
   unban:
      description: unbans player
      usage: /<command> <player> - unbans player
   checkban:
      description: checks if a player is banned
      usage: /<command> <player> - checks if a player is banned
   search:
      description: search function
      usage: /<command> p:<player> t:<type> i:<id>
   serubans:
      description: debug
      usage: /<command> <-arg> - debug/export
      
permissions:
  serubans.*:
    description: gives full permission on Serubans.
    children:
      serubans.ban: true
      serubans.tempban: true
      serubans.kick: true
      serubans.warn: true
      serubans.unban: true
      serubans.checkban: true
      serubans.debug: true
      serubans.broadcast: true
 