name: SeruBans
main: net.serubin.serubans.SeruBans
version: 0.1

commands:
   ban:
      description: Bans player
      usage: /<command> <player> <reason> - bans player
   tempban:
      description: tempbans player
      usage: /<command> <player> <amount> <unit> <reason> - tempbans player
   kick:
      description: kicks player
      usage: /<command> <player> <reason> - kicks player
   warn:
      description: warns player
      usage: /<command> <player> <reason> - warns player
   unban:
      description: unbans player
      usage: /<command> <player> - unbans player
   checkban:
      description: checks if a player is banned
      usage: /<command> <player> - checks if a player is banned
   sbuser:
      description: debug
      usage: /<command> - lists users